### ISSUE TITLE
Keep original "duotone" light background ?

### ISSUE THREAD

**Issue by MoOx** [5310/duotone-bright-sea-syntax#1]
A white background is very violent for the eyes.

I had to add this CSS to revert the original color of @simurai duotone light theme.

``` css
.theme-duotone-bright-sea-syntax atom-text-editor {
  background-color: hsl(40, 33%, 97%); /* https://github.com/simurai/duotone-light-syntax/blob/master/styles/colors.less */
}
```

Maybe this should be the default background color for this version?
